server:
  port: 7539
  servlet:
    context-path: /api

spring:
  application:
    name: api-platform-interface-info
  cloud:
    nacos:
      discovery:
        server-addr: localhost:9527
  # DataSource Config
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/api_platform
      username: root
      password: 123456
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 0
    password: Redis@1234!

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# Feign调试日志是以debug级别来输出的，而springboot的默认日志级别是info，可以仅仅指定Feign接口所在包的路径为debug级别
logging:
  level:
    com.xuan.client: debug

feign:
  client:
    config:
      default:
        logger-level: BASIC
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50

knife4j:
  enable: true
  openapi:
    title: ${spring.application.name}-openapi
    description: ${spring.application.name}-openapi
    concat: "xuan"
    version: v1.0
    license: Apache 2.0
    group:
      default:
        group-name: "default"
        api-rule: package
        api-rule-resources:
          - com.xuan.controller