server:
  port: 6789
  servlet:
    context-path: /api/v1
  tomcat:
    keep-alive-timeout: -1

spring:
  application:
    name: api-platform-interface-v1
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8088
  # DataSource Config
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/date_information
      username: root
      password: 123456
#      initial-size: 1
#      min-idle: 2
#      max-active: 10
  redis:
    host: localhost
    port: 6379
    password: Redis@1234!


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
